### PR TITLE
Add Grunt inline facility

### PR DESCRIPTION
**Pull request by Zboule**
Add Grunt build for :
- Compile scss
- Inline css into html

The documentation have been update

### CODE REVIEW

**Comment by derekpunsalan** [comment]
@jordaneCure awesome! I'll take a look at this closer this evening.

**Comment by Zboule** [comment]
Just see their is a small issue with "grunt-inline-css"
"grunt-inline-css ": "^0.4.0"   must be add in package.json

Not sure how to edit the merge request

Le ven. 22 avr. 2016 à 13:08, Derek Punsalan notifications@github.com a
écrit :

**Comment by derekpunsalan** [comment]
Followed your setup suggestions and am having trouble building as-is. I like the idea though, and can reconfigure the project to take advantage of some of the automation.

**Comment by Zboule** [comment]
If you need help, i can help you

Le mar. 26 avr. 2016 à 00:29, Derek Punsalan notifications@github.com a
écrit :

**Pull request closed without merging**
